export const ETHEREUM_ERROR_CODES = [
  'CALL_EXCEPTION',
  'INSUFFICIENT_FUNDS',
  'NETWORK_ERROR',
  'NONCE_EXPIRED',
  'REPLACEMENT_UNDERPRICED',
  'TRANSACTION_REPLACED',
  'UNPREDICTABLE_GAS_LIMIT',
] as const;
export type EthereumErrorCode = typeof ETHEREUM_ERROR_CODES[number];
